hl.on("hyprland.start", function()
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("kdeconnectd & vicinae server")
	hl.exec_cmd("noctalia-shell -d & awww-daemon")
	hl.exec_cmd("awww img ~/.dotfiles/moduli/wallpaper.png")
	hl.exec_cmd("nm-applet & udiskie")
	hl.exec_cmd("kdeconnect-indicator & pypr")
	hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 18")
	hl.exec_cmd("clipse -listen")
end)
