name: "Build"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  nixos:
    name: "nixosConfigurations.${{ matrix.host }}"
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: GiovanGianFranco
            runner: ubuntu-latest
          - host: rpi5
            runner: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: cronos6096
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build toplevel
        run: |
          nix build \
            ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --no-link \
            --print-build-logs
