name: "Build"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  nixos:
    name: "nixosConfigurations.${{ matrix.host }}"
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: GiovanGianFranco
            runner: ubuntu-latest
          - host: rpi5
            runner: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}-
          gc-max-store-size-linux: 7516192768  # 7 GiB (10 GiB limit)

      - name: Build toplevel
        run: |
          nix build \
            ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --no-link \
            --print-build-logs
