name: "Build"

on:
  push:
    branches: [master]
  pull_request:

jobs:
  nixos:
    name: "nixosConfigurations.${{ matrix.host }}"
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: GiovanGianFranco
            runner: x86_64-linux
          - host: rpi5
            runner: aarch64-linux

    steps:
      - uses: actions/checkout@v4

      - name: Build toplevel
        run: |
          nix build \
            ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel" \
            --no-link \
            --print-build-logs
